import NavBar from "@components/NavBar";
import Head from "next/head";

export const siteTitle = "Hope";

export default function Layout({ children, home, isBusinessPage }) {
  return (
    <>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className="text-4xl font-bold">{siteTitle}</h1>
      </header>
      <div>
        <main>{children}</main>
        {!home ? <NavBar isBusinessPage={isBusinessPage} /> : null}
      </div>
    </>
  );
}
